version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: next
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
  - dependency-name: ts-loader
    versions:
    - 8.0.15
    - 8.0.16
    - 8.0.17
    - 8.1.0
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: swiper
    versions:
    - 6.4.10
    - 6.4.11
    - 6.4.12
    - 6.4.14
    - 6.4.15
    - 6.4.9
    - 6.5.5
    - 6.5.6
    - 6.5.7
  - dependency-name: tailwindcss
    versions:
    - 2.0.4
    - 2.1.1
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: sass-loader
    versions:
    - 11.0.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
